<?php
require_once '../../conexion.php';
require_once 'fpdf/fpdf.php';
$pdf = new FPDF('P', 'mm', array(100, 180));
$pdf->AddPage();
$pdf->SetMargins(7, 0, 0);
$pdf->SetTitle("Ventas");
$pdf->SetFont('Arial', 'B', 12);
$id = $_GET['v'];
$idcliente = $_GET['cl'];
$config = mysqli_query($conexion, "SELECT * FROM configuracion");
$datos = mysqli_fetch_assoc($config);
$clientes = mysqli_query($conexion, "SELECT * FROM cliente WHERE idcliente = $idcliente");
$datosC = mysqli_fetch_assoc($clientes);
$historialv = mysqli_query($conexion, "SELECT * FROM ventas WHERE id = $id");
$datosV = mysqli_fetch_assoc($historialv);
$ventas = mysqli_query($conexion, "SELECT d.*, p.codproducto, p.descripcion FROM detalle_venta d INNER JOIN producto p ON d.id_producto = p.codproducto WHERE d.id_venta = $id");
$pdf->Cell(65, 5, utf8_decode('DROMEDIC JC FARMA'), 7, 5, 'L');
$pdf->Ln(); 
 
$pdf->image("../../assets/img/Logos2.png", 70, 4, 24, 15, 'PNG');
$pdf->SetFont('Arial', 'B', 8);
$pdf->Ln(); 
$pdf->Cell(35, 5, utf8_decode("Teléfono Empresa: "), 0, 0, 'L');
$pdf->SetFont('Arial', '', 8);
$pdf->Cell(15, 5, '314 643 4346', 5, 1, 'L');
$pdf->SetFont('Arial', 'B', 8);
$pdf->Cell(35, 5, utf8_decode("Dirección Drogueria: "), 0, 0, 'L');
$pdf->SetFont('Arial', '', 8);
$pdf->Cell(15, 5, utf8_decode('Barrio las quintas Cr 7 #53-73'), 0, 1, 'L');
$pdf->SetFont('Arial', 'B', 8);
$pdf->Cell(35, 5, "Correo Electronico: ", 0, 0, 'L');
$pdf->SetFont('Arial', '', 8);
$pdf->Cell(15, 5, utf8_decode('dromedic2009@gmail.com'), 0, 1, 'L');
$pdf->Ln();
$pdf->SetFont('Arial', 'B', 8);
$pdf->SetFillColor(0, 0, 0);
$pdf->SetTextColor(255, 255, 255);
$pdf->Ln(); 
$pdf->Cell(87, 5, "Datos del cliente", 1, 1, 'C', 1);
$pdf->SetTextColor(0, 0, 0);
$pdf->Cell(4, 5, utf8_decode('#'), 0, 0, 'L');
$pdf->Cell(15, 5, utf8_decode('Nombre'), 0, 0, 'L');
$pdf->Cell(18, 5, utf8_decode('Teléfono'), 0, 0, 'L');
$pdf->Cell(20, 5, utf8_decode('Dirección'), 0, 0, 'L');
$pdf->Cell(20, 5, utf8_decode('Fecha Registro'), 0, 1, 'L');
$pdf->SetFont('Arial', '', 8);
$pdf->Cell(5, 5, utf8_decode($datosV['id']), 0, 0, 'L');
$pdf->Cell(14, 5, utf8_decode($datosC['nombre']), 0, 0, 'L');
$pdf->Cell(19, 5, utf8_decode($datosC['telefono']), 0, 0, 'L');
$pdf->Cell(19, 5, utf8_decode($datosC['direccion']), 0, 0, 'L');
$pdf->Cell(21, 5, utf8_decode($datosV['fecha']), 0, 1, 'L');

$pdf->Ln(3);
$pdf->Ln(); 
$pdf->SetFont('Arial', 'B', 8);
$pdf->SetTextColor(255, 255, 255);
$pdf->Cell(87, 5, "Detalle de Producto", 1, 1, 'C', 1);
$pdf->SetTextColor(0, 0, 0);
$pdf->Cell(40, 5, utf8_decode('Descripción'), 0, 0, 'L');
$pdf->Cell(16, 5, 'Cant.', 0, 0, 'L');
$pdf->Cell(15, 5, 'Precio', 0, 0, 'L');
$pdf->Cell(15, 5, 'Sub Total.', 0, 1, 'L');
$pdf->SetFont('Arial', '', 8);
$total = 0.00;
$desc = 0.00;
while ($row = mysqli_fetch_assoc($ventas)) {
    $pdf->Cell(40, 5, $row['descripcion'], 0, 0, 'L');
    $pdf->Cell(16, 5, $row['cantidad'], 0, 0, 'L');
    $pdf->Cell(15, 5, $row['precio'], 0, 0, 'L');
    $sub_total = $row['total'];
    $total = $total + $sub_total;
    $desc = $desc + $row['descuento'];
    $pdf->Cell(15, 5, number_format($sub_total, 2, '.', ','), 0, 1, 'L');
}
$pdf->Ln();
$pdf->Ln(); 
$pdf->Ln(); 
$pdf->Ln(); 
$pdf->SetFont('Arial', 'B', 10);
$pdf->Cell(86, 5, 'Descuento Total', 0, 1, 'R');
$pdf->SetFont('Arial', '', 9);
$pdf->Cell(86, 5, number_format($desc, 2, '.', ','), 0, 1, 'R');
$pdf->SetFont('Arial', 'B', 10);
$pdf->Cell(86, 5, 'Total Pagar', 0, 1, 'R');
$pdf->SetFont('Arial', '', 9);
$pdf->Cell(86, 5, number_format($total, 2, '.', ','), 0, 1, 'R');

$pdf->Output("ventas.pdf", "I");

?>